### ISSUE TITLE
关于孤独感

### ISSUE THREAD

**Issue by Ark2000** [Ark2000/k2kra-blogs#4]
first edit: 2024-01-11-19-09

今天感冒了，躺在出租屋的床上病的要死，又冷又热，手机一直嗡嗡响个没完没了，拿起来一看，要么是惦记着我的剩余价值，让我贷款买车的骚扰电话，要么是学校的，青年大学习，离校登记、订票通知、学院开会，长长的一大截，这些冗长无用的例行通知只让我感到恶心。要么是一些无聊的通知短信，XX节日，快递到了，流量剩余，看一眼就可以彻底忘掉的信息。（感冒了，没人理）

有些悲凉，一种前所未有的孤独感像海啸一样将我吞噬。就算我心脏病突发猝死在这间八平米的出租屋里面，至少也得等到开春了尸体发臭才会有人发现吧？（很孤独）

我本是是一个感性凌驾于理性之上的人，但不代表总是这样，当自己的情绪到达一个很低的阈值之时，理性就会重新占据上风，阻止感性的进一步自由落体，击穿我的清醒极限。（想办法）

完全脱离人与人之间的交流对我的身体健康应该没有什么影响，但是我生而为人，就代表无法克服基因中的倾向本能，一直处于没有任何交流的状态应该会对我的精神健康产生很大的影响，从理性的角度来看，我不能忽视这一点，因此，理性人格占据主要的大脑耗能，产出一些应对策略。（可有可无的废话）

首先想到的，自然就是主动在现实世界中与更多的人建立更多的关联，比如参加更多的活动，多出去走走等等，这是最容易想到的策略，因为它说起来很简单，但是，执行的时候，并不是选择题，也不是填空题，而是他妈的一千二百字的自由发挥的作文，我不擅长写作文。（多走走）

最好的方式，我想，大概就是成为一个创造者，一个内容生产者，生产文字，生产代码，生产图片，生产视频，生产高质量的内容，吸引更多的人来消费自己产生的内容，而不是一直这样精神内耗下去。如果你本身是一张白纸，却总是希望有人前来阅读，和你建立关联，无疑只会永远等待下去。相反，如果你是一本精彩的书，那么又怎么会担心永远被放在阴暗的角落呢？（多产出）

（总结：多产出，应对孤独感）

**Comment by Attack825** [comment]
八平米的出租屋真让人压抑，或许可以找人玩玩联机游戏或者户外爱好
